# Generated by Django 4.1.7 on 2023-03-08 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import rudderstack.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('gst_details', models.JSONField(default=dict)),
                ('business_owner', models.UUIDField()),
                ('image_id', models.UUIDField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Disabled'), (3, 'Blocked')], default=1)),
                ('available_credits', models.IntegerField(default=0, validators=[rudderstack.validators.Validators.min_0_validator])),
                ('business_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BusinessUserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('user_id', models.UUIDField()),
                ('role', models.IntegerField(choices=[(1, 'Owner'), (10, 'Admin'), (20, 'Reporter')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Disabled'), (3, 'Blocked')], default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.businessmodel')),
            ],
            options={
                'db_table': 'business_user',
                'managed': True,
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessConfigurationsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('facebook_ads_config', models.JSONField(default=dict)),
                ('google_ads_config', models.JSONField(default=dict)),
                ('active_plan', models.UUIDField(null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.businessmodel')),
            ],
            options={
                'db_table': 'business_configurations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BusinessTransactionLedgerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('credits', models.IntegerField(validators=[rudderstack.validators.Validators.min_0_validator])),
                ('is_credit', models.BooleanField()),
                ('created_by', models.UUIDField(null=True)),
                ('reference_id', models.UUIDField()),
                ('reference_type', models.IntegerField(choices=[(1, 'Order')])),
                ('expiry_date_time', models.DateTimeField(null=True)),
                ('credits_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='business.businessmodel')),
            ],
            options={
                'db_table': 'business_transaction_ledger',
                'managed': True,
                'unique_together': {('reference_type', 'reference_id', 'is_credit')},
                'index_together': {('business', 'is_active', 'is_deleted')},
            },
        ),
    ]
