# Generated by Django 4.1.7 on 2023-03-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesstransactionledgermodel',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='businesstransactionledgermodel',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='businesstransactionledgermodel',
            name='business',
        ),
        migrations.DeleteModel(
            name='BusinessConfigurationsModel',
        ),
        migrations.DeleteModel(
            name='BusinessTransactionLedgerModel',
        ),
    ]
